### ISSUE TITLE
Banner

### ISSUE THREAD

**Issue by tonifisler** [antistatique/antistatique.net#12]
Display a banner at the top of the page. -> https://projects.invisionapp.com/d/main#/console/1442313/56272312/preview

![screen shot 2015-03-13 at 20 31 16](https://cloud.githubusercontent.com/assets/1708450/6645833/f323ee08-c9bf-11e4-8bdf-5c3633362af8.png)

We need to disable completely the node page for this content type. It's useless. :wine_glass: 

I suggest adding this module for that: https://www.drupal.org/project/rabbit_hole

| Field | Type | Full | Required | Comment |
|-------|------|:----:|:------:|:--------:|---------|
| title | text | ✔︎ | Yes | |
| subtitle | text | ✔︎ | Yes | |
| icon | image | ✔︎ | | |

We could add an icon at the left in some cases! No?

**Comment by tonifisler** [comment]
ping @zufrieden @gido @guillaumeberry

**Comment by tonifisler** [comment]
Or a font-awesome text field! Yay!

**Comment by gido** [comment]
@tonifisler My review:

- [ ] Maybe subtitle could be a textarea instead of input text field. I want to be able to insert links (like to an open job position)
- [ ] Under "Fontawesome class" Add link to the documentation of Fontawesome where we can choose an icon
- [ ] Add field for  date from / to

**Comment by zufrieden** [comment]
After discussion, we don't need this content type. #45 we'll use a block and assign it a region manually.
- [ ] delete banner content type
