### ISSUE TITLE
Project tile styleguide

### ISSUE THREAD

**Issue by zufrieden** [antistatique/antistatique.net#127]

**Comment by tonifisler** [comment]
Je propose un nouveau champ pour l'image de ce teaser. Comme ça c'est pas la même que la hero-image. Vous en pensez quoi @zufrieden et @guillaumeberry ?

**Comment by zufrieden** [comment]
Bonne idée ! @tonifisler

2015-03-20 16:25 GMT+01:00 tonifisler <notifications@github.com>:

> Je propose un nouveau champ pour l'image de ce teaser. Comme ça c'est pas
> la même que la hero-image. Vous en pensez quoi @zufrieden
> <https://github.com/zufrieden> et @guillaumeberry
> <https://github.com/guillaumeberry> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/antistatique/antistatique.net/issues/127#issuecomment-84048765>
> .
>



-- 
---
Marc Friederich
marc@antistatique.net

Antistatique <http://antistatique.net/>
rue de Sébeillon 9b
1004 Lausanne
+41 21 623 63 03
www.antistatique.net

**Comment by guillaumeberry** [comment]
:+1: 

Go, go, go !
(on va bien s'amuser)
