### ISSUE TITLE
Responsive main navigation

### ISSUE THREAD

**Issue by tonifisler** [antistatique/antistatique.net#130]

**Comment by zufrieden** [comment]
@guillaumeberry please review

**Comment by tonifisler** [comment]
I think we need to add a background or something behind the **&times; Close** button. It gets unreadable on certain cases.

**Comment by guillaumeberry** [comment]
What do you think guys? @zufrieden @tonifisler 
![responsive-nav-mobile](https://cloud.githubusercontent.com/assets/1800253/7839803/a768aab6-0494-11e5-9d3c-86ad7c238ab8.png)
![responsive-nav-tablet](https://cloud.githubusercontent.com/assets/1800253/7839804/a76be35c-0494-11e5-83fa-f2f1d5cfd9fa.png)

**Comment by tonifisler** [comment]
I think the arrow is not quite the best solution... Maybe a **&times;** would be better?

**Comment by zufrieden** [comment]
I'm ok with the arrow. But it would be better to have this close button at
the center.

On Wed, May 27, 2015 at 5:24 PM, tonifisler <notifications@github.com>
wrote:

> I think the arrow is not quite the best solution... Maybe a *×* would be
> better?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/antistatique/antistatique.net/issues/130#issuecomment-105956326>
> .
>



-- 
---
Marc Friederich
marc@antistatique.net

Antistatique <http://antistatique.net/>
rue de Sébeillon 9b
1004 Lausanne
+41 21 623 63 03
www.antistatique.net

**Comment by gido** [comment]
Testé, c'est pas encore ça

**Comment by guillaumeberry** [comment]
@gido I know… On it!

**Comment by guillaumeberry** [comment]
![responsive-nav](https://cloud.githubusercontent.com/assets/1800253/7885567/e9b3bcd0-0624-11e5-8f8d-52f8befef156.png)
poke @zufrieden @tonifisler Make a wish/choice/guess/review/feedback/decision :hamster:

**Comment by tonifisler** [comment]
I would say **n°2** with a full-width button. Seems to be the best solution.

We need to have a clear "Contact us" button that is separated from the rest of the menu (unlike n°8) because it is the same URL as "With you" (...me no like it...) and because we already have the paper-plane when the menu is collapsed. The user who doesn't understand this paper-plane should be able to find how to contact us nevertheless.

Full-width for the "Contact us" button seems a better idea since the logo is franc bord.

And I'd like the **french - english** better as **fr-en** and the "Close" button without its label. :)

#ClientPasChiant

**Comment by guillaumeberry** [comment]
Updated, dear client!

**Comment by zufrieden** [comment]
Ok for version 2 with a small change check this
![new_menu](https://cloud.githubusercontent.com/assets/451236/7965765/ed3edf98-0a1f-11e5-84fc-d6eea8a9fe84.png)

**Comment by guillaumeberry** [comment]
Are we good with this? @tonifisler @zufrieden 
![final-final](https://cloud.githubusercontent.com/assets/1800253/7981386/e2a4baf0-0aae-11e5-887e-72ec1667e9c2.png)

**Comment by zufrieden** [comment]
Yes. Now we have to design transitions

**Comment by tonifisler** [comment]
So is there a `box-shadow` on the image? Or is it on the dropdown too, to be sure the "**&times; Menu**" is readable on all backgrounds?

**Comment by guillaumeberry** [comment]
You can probably use the same gradient that we have on cover images (inverted, height:48px). This gradient is here so xMenu is readable no matter the background (so always in white).

Source files are here:
/Projects/001_antistatique_communication/Communication/5_site_web/maquettes-new-site-2015/Navigation-responsive.ai

**Comment by tonifisler** [comment]
Ok so I had to write the lang-switcher as it is on desktop. We should re-write the preprocessor to display the whole language string, but I didn't want to waste time on it more than I already did...

**Comment by guillaumeberry** [comment]
- [ ] One tiny pixel left at the top of the menu (we see the image below)
- [ ] Language change is too small
- [ ] Hamburger glyph is a bit too wide (16px width in the mockups)

Apart from this, all good for V1.0!

**Comment by tonifisler** [comment]
> One tiny pixel left at the top of the menu (we see the image below)

Was already done in commit just before your comment :wink:

**Comment by guillaumeberry** [comment]
:heart_eyes:
