### ISSUE TITLE
taxonomy view

### ISSUE THREAD

**Issue by zufrieden** [antistatique/antistatique.net#132]
For instance /fr/category/expliquons 
And more generaly, how to avoid not having a container on generic pages

---

**Guillaume's feedback:**

- [x] 1 colonne
- [x] breadcrumb
- [x] ~~titre aligné sur la colonne~~
- [x] cover (random pattern pour l'instant)
- [x] du coup le titre pourrait être dans sur le cover…

**Comment by zufrieden** [comment]
done except for header part

**Comment by tonifisler** [comment]
Retour de @guillaumeberry dans la description de l'issue.

**Comment by zufrieden** [comment]
:+1:
