### ISSUE TITLE
Add a contact page

### ISSUE THREAD

**Issue by zufrieden** [antistatique/antistatique.net#134]
- [x] Finish contact page design https://projects.invisionapp.com/d/main#/console/3571712/78011990/preview
- [x] Create page
- [x] Update footer links (Lausanne & Geneva)
- [x] Translate the form (add a second one)

- [x] Fix Notices

> Notice: Undefined index: node in antistatique_preprocess_page() (line 95 of /Users/toni/Sites/Antistatique/antistatique.net/drupal/sites/all/themes/antistatique/template.php).

**Addendum**:

Something was said about a map? :)

**Comment by zufrieden** [comment]
https://projects.invisionapp.com/share/N638VPB4W#/screens/83270126?maintainScrollPosition=false designed, now @tonifisler is coding ;-)

**Comment by tonifisler** [comment]
Reviewed by @gido
