### ISSUE TITLE
Breadcrumb frontend

### ISSUE THREAD

**Issue by zufrieden** [antistatique/antistatique.net#135]
/styleguide/components_-_breadcrumb.html
- [ ] Dropdown list
- [ ] Active, hover effect

**Comment by tonifisler** [comment]
I need review for this @nsz :wink: It seems to be working on every page, but need to be sure.

**Comment by zufrieden** [comment]
- [ ] Not working on 'work' sections 
- [ ] Add fallback option/select on mobile as the html dropdown is bad UX on mobile

**Comment by tonifisler** [comment]
Complicated to make it toggle on `window.resize`... But it works for mobile/desktop now.

**Comment by gido** [comment]
Tested on Chrome Android
