### ISSUE TITLE
Breadcrumb backend

### ISSUE THREAD

**Issue by zufrieden** [antistatique/antistatique.net#136]
Create a module to handle breadcrumb (dropdown sibling listing)
Only last level can expand to a dropdown list

**Comment by tonifisler** [comment]
We'll need @gido's magic fingers for this.

**Comment by zufrieden** [comment]
Yes mais si tu commence avec le styleguide ça va lui faciliter la tâche

**Comment by guillaumeberry** [comment]
:+1:

**Comment by tonifisler** [comment]
Problem that I'll leave to @gido 

:door: :runner: 

![screen shot 2015-04-22 at 16 02 17](https://cloud.githubusercontent.com/assets/1708450/7276333/397d9882-e909-11e4-9d2e-c768669ad521.png)

I need to remove the label of the 404 and 403 pages from the dropdown but keep it in the button label. :)

**Comment by zufrieden** [comment]
My comment are in a new issue #162
