### ISSUE TITLE
Change thank you page for newsletter subscription

### ISSUE THREAD

**Issue by tonifisler** [antistatique/antistatique.net#138]
- [x] Create thank you page
- [x] Create a new list for English people
- [x] Apply link of English list in corresponding Drupal Block
- [x] Change redirect pages on Campaign Monitor (when production ready)

**Comment by tonifisler** [comment]
Added in staging: 

- http://staging.antistatique.net/fr/nous/vous-remercions FR
- http://staging.antistatique.net/en/we/thank-you EN

I'd suggest we create two lists, and send two versions of our newsletters. One in English and one in French. Ok?

**Comment by guillaumeberry** [comment]
:+1:

**Comment by zufrieden** [comment]
:+1: go ;-)

**Comment by gido** [comment]
Done. Need review
