### ISSUE TITLE
Paragraphs tweaks

### ISSUE THREAD

**Issue by tonifisler** [antistatique/antistatique.net#139]
- ~~Add paragraph with **Big fontawesome/smashicons icon** + **Body** (for Drupal, etc)~~
- [x] Add possibility to choose `background-color` for **image wide** paragraph
- ~~Add this paragraph style~~
![screenshot 2015-04-20 21 57 53](https://cloud.githubusercontent.com/assets/451236/7239217/5c40ade4-e7a8-11e4-9ec6-3a3706fbe17a.png)
- [x] Make paragraphe work on EN/FR

**Comment by zufrieden** [comment]
little update on this issue @tonifisler

**Comment by tonifisler** [comment]
Need @guillaumeberry's ideas for smashicons Paragraphs!
