### ISSUE TITLE
Add Hero image to the last 20 articles

### ISSUE THREAD

**Issue by zufrieden** [antistatique/antistatique.net#154]
- [x] 1) UX Lausanne
- [x] 2) Athena 
- [x] 3) Frontend meetup
- [x] 4) Design graphique : ONG et associations : améliorer les dons en ligne (Part.2)
- [x] 5) Interaction15 conference — San Francisco baby! 
- [x] 6) JSON-LD avec Google Tag Manager
- [x] 7) User Experience / UX : ONG et associations : améliorer les dons en ligne (Part.1)
- [x] 8) DPM UK Conf
- [x] 9) User Experience / UX : just enough research by Erika Hall
- [x] 10) Genève? Enchanté!
- [x] 11) User Experience / UX : les tests utilisateurs
- [x] 12) Tests utilisateurs vendredi 6 février recevez 40.- pour 30 minutes !
- [x] 13) User Experience / UX : les Mega menus
- [x] 14) Et encore une ! (en attente de l'envoi de Marion)
- [x] 15) Une fille de plus chez Antistatique
- [x] 16) Ça Fyuse
- [x] 17) Tests utilisateurs mercredi 7 janvier recevez 40.- pour 30 minutes !
- [x] 18) L’équipe s’agrandit
- [ ] 19) Bonjour Genève, nous sommes une agence web. (en attente de la photo d'Alberto)
- [x] 20) N’appelez pas les gens des ressources

**Comment by nsz** [comment]
[] 1) UX Lausanne
[x] 2) Athena http://staging.antistatique.net/fr/nous/bloggons/2015/03/25/athena-une-application-de-gestion-pour-les-federations-sportives
[x] 3) Frontend meetup http://staging.antistatique.net/fr/nous/bloggons/2015/03/25/frontend-romandie-meetup
[] 4) Design graphique : ONG et associations : améliorer les dons en ligne (Part.2)
[x] 5) Interaction15 conference — San Francisco baby! http://staging.antistatique.net/fr/nous/bloggons/2015/02/24/interaction15-conference-san-francisco-baby
[] 6) JSON-LD avec Google Tag Manager
[] 7) User Experience / UX : ONG et associations : améliorer les dons en ligne (Part.1)
[] 8) DPM UK Conf
[] 9) User Experience / UX : just enough research by Erika Hall
[] 10) Genève? Enchanté!
[] 11) User Experience / UX : les tests utilisateurs
[] 12) Tests utilisateurs vendredi 6 février recevez 40.- pour 30 minutes !
[] 13) User Experience / UX : les Mega menus
[] 14) Et encore une !
[] 15) Une fille de plus chez Antistatique
[] 16) Ça Fyuse
[] 17) Tests utilisateurs mercredi 7 janvier recevez 40.- pour 30 minutes !
[] 18) L’équipe s’agrandit
[] 19) Bonjour Genève, nous sommes une agence web.
[] 20) N’appelez pas les gens des ressources
