### ISSUE TITLE
Bloc socialize frontend

### ISSUE THREAD

**Issue by zufrieden** [antistatique/antistatique.net#155]

**Comment by zufrieden** [comment]
- [ ] 1 par langue

**Comment by guillaumeberry** [comment]
Je like ! #CestTout

**Comment by tonifisler** [comment]
- 326b496  remove unused svgs socialize
- 6a5fb58  fix horizontal scroll bug on socialize block
- 3bd4084  fix socialize bg position on mobile
- ab6737a  add socialize element

**Comment by tonifisler** [comment]
mmmmmmh missing the translation here, aren't we?

**Comment by zufrieden** [comment]
- [ ] Nous socializons en SVG @guillaumeberry 
- [ ] Créer le bloc FR et EN, checker les liens
- [ ] Ne devrait-il pas apparaitre aussi sur la homepage et sur la page "With you" ? Pour moi oui.

**Comment by guillaumeberry** [comment]
Du genre ça ?
![nous-socialisons-genre](https://cloud.githubusercontent.com/assets/1800253/7879224/d091e2c6-05ee-11e5-8036-19559093126c.png)

**Comment by dmrrlc** [comment]
Vraiment pas centré en EN
![socialize](https://cloud.githubusercontent.com/assets/657282/7884459/3f054476-061e-11e5-85df-6d1ecf9e4fe3.png)

**Comment by guillaumeberry** [comment]
@dmrrlc normal :p

**Comment by tonifisler** [comment]
Done! ready for review, master @guillaumeberry

**Comment by guillaumeberry** [comment]
Ok. Works on desktop. But we need to fix it in the device lab for tablets & :phone:
