### ISSUE TITLE
Error on menu views_plugin_style_jump_menu->render() (line 149

### ISSUE THREAD

**Issue by zufrieden** [antistatique/antistatique.net#158]

**Comment by zufrieden** [comment]
http://staging.antistatique.net/fr/nous/bloggons/2015/02/24/interaction15-conference-san-francisco-baby

Notice: Undefined index: absolute in views_plugin_style_jump_menu->render() (line 149 of /home/antistatique/www/staging.antistatique.net/releases/20150505113127/drupal/sites/all/modules/views/plugins/views_plugin_style_jump_menu.inc).

**Comment by zufrieden** [comment]
Error comes from the fact that we try to display the current node in the dropdown breadcrumb. 

Easy fix : remove this feature
small fix : add a patch which hide the error (https://www.drupal.org/node/2272387)
Good fix : Fix the problem not the symptoms ...  when for instance (we don't want to display list of all articles in the breadcrumb)

@gido WDYT ?

**Comment by gido** [comment]
@tonifisler Fixed in f411d13665865b6a551d7c3f5b45fac366b7fa16 ?
