### ISSUE TITLE
Rework H hierarchy H1 to H6

### ISSUE THREAD

**Issue by zufrieden** [antistatique/antistatique.net#159]

**Comment by guillaumeberry** [comment]
I reworked those styles, check them here:
https://dl.dropboxusercontent.com/u/6924/font-sizes/index.html

@zufrieden please review & comment, thanks ;)

**Comment by zufrieden** [comment]
- Not responsive yet ?
- For me the the thin font should not be used for H5 .... to small see screenshot (Chrome)
![screenshot 2015-05-28 17 07 30](https://cloud.githubusercontent.com/assets/451236/7863350/2288e964-055c-11e5-8bbd-ccf81b17cc00.png)
![screenshot 2015-05-28 17 07 41](https://cloud.githubusercontent.com/assets/451236/7863351/228c2a34-055c-11e5-8c09-8ceb2170343e.png)

**Comment by zufrieden** [comment]
especially on dark background ...
