### ISSUE TITLE
Migrer les derniers articles du blog

### ISSUE THREAD

**Issue by zufrieden** [antistatique/antistatique.net#160]

**Comment by zufrieden** [comment]
- [ ] Il ne manque que celui-ci http://antistatique.net/blog/2015/05/28/expo-milano-2015-pavillon-suisse/ @ludovicrenevey tu t'en occupes ?

**Comment by dmrrlc** [comment]
@ludovicrenevey je l'ai migré, est-ce que tu peux juste réuploader les images stp?

**Comment by dmrrlc** [comment]
need #198
