### ISSUE TITLE
Tweak header with/height on every breackpoint

### ISSUE THREAD

**Issue by zufrieden** [antistatique/antistatique.net#161]
- [x]  remove white top gradiant

**Comment by tonifisler** [comment]
I'd suggest removing the resize on height breakpoints. The image ratio is never the same and it often looks terrible...

**Comment by tonifisler** [comment]
Let's put this in images:

## #FancyBigDesktop
![screen shot 2015-05-20 at 10 55 23](https://cloud.githubusercontent.com/assets/1708450/7722274/f793d27e-fede-11e4-8d41-ffb1eaa16e0e.png)

## #UglyNotSoBigDesktop
![screen shot 2015-05-20 at 10 55 46](https://cloud.githubusercontent.com/assets/1708450/7722294/1c794448-fedf-11e4-815e-84308c5c3563.png)

**Comment by zufrieden** [comment]
:+1: reviewed
