### ISSUE TITLE
Let's fix breadcrumbs

### ISSUE THREAD

**Issue by zufrieden** [antistatique/antistatique.net#162]
- [x] fix link to /fr/nous/travaillons in portfolio detail breadcrumb (in the template)

- [x] In 4 important pages (Home, We, Work, With you) remove the breadcrumb as there is no siblings

## In "We" sub pages
- [x] Add a link to "/fr/nous" on word "nous" (in the template) 
- [x] in "We" sub pages we should have : 
  - [x] ~~are antistatique~~ as it's a 1st level page
  - [X] Are a team
  - [X] have a philosophy
  - [X] hire
  - [X] socialize
  - [x] Blog
  - [X] Send newsletter 
  - [x] ~~No tagline~~ 

### In "we" "blog" about "food"
- [x] Fix articles detail breadcrumb list set current category (will then remove bug #158)

## In "work" Sub pages
- [x] Add a link to "/fr/we/work" on word "faisons" (in the template)
- [x] in "Work" sub pages we should have
  - [x] ~~du beau travail pour le WWW~~ as it's a 1st level page
  - [X] de la stratégie
  - [X] du design
  - [X] du UX Design
  - [X] du développement
  - [X] De la formation et de l'accompagnement
  - [x] avec (link to portfolio view)

### In "work" / "with" / "Client name"
- [x] Add another breadcrumb case in template "we a[href=/fr/we/work]work[/] a[href=/fr/we/work/with]with[/] people from [portfolio client name list]
- [x] Add a link to "/fr/we/work" on word "faisons" (in the template)
- [x] Add a link to portfolio list view on word "with"  (in the template)

**Comment by tonifisler** [comment]
@zufrieden: "In 4 important pages (Home, We, Work, With you) remove the breadcrumb as there is no siblings"

Temporarily? on the homepage, ok. But not the others, right?
