### ISSUE TITLE
Teammate that are no longer here pages

### ISSUE THREAD

**Issue by guillaumeberry** [antistatique/antistatique.net#165]
Complete their profile page so their blog posts are displayed correctly:

- [ ] Profile picture
- [ ] Hero image
- [ ] Some social link
- [ ] Job title
- [ ] Short bio (from twitter for instance

**Comment by tonifisler** [comment]
Shouldn't we disable completely their profile page? We only need the name and image for the blogposts.

**Comment by guillaumeberry** [comment]
Marc said to keep their profile page. It's there, crawled by Google, not linked in our pages but is exists.

**Comment by tonifisler** [comment]
This page will be linked from the blog articles.

**Comment by guillaumeberry** [comment]
Profile picture added for non-working girls & boys.
