### ISSUE TITLE
Blog : category : bad display

### ISSUE THREAD

**Issue by nsz** [antistatique/antistatique.net#168]
### What we have
![capture d ecran 2015-05-18 a 12 09 35](https://cloud.githubusercontent.com/assets/1941982/7678797/328572d6-fd57-11e4-8885-07d176f8f640.png)

The category **Lisons** doesn't appear.

### What we want
7.04.2014 › by Marc in **Lisons**

**Comment by tonifisler** [comment]
Fixed. Categorsy name was missing in backend... :/
