### ISSUE TITLE
Header dark-light color issues

### ISSUE THREAD

**Issue by tonifisler** [antistatique/antistatique.net#172]
That Contact Button... My eyes are bleeding. 

Shouldn't we switch it to a white background too?

cc/ @guillaumeberry @zufrieden 

![screen shot 2015-05-21 at 11 13 50](https://cloud.githubusercontent.com/assets/1708450/7745327/ae4a4a0e-ffaa-11e4-9add-f7c486839cf6.png)

**Comment by zufrieden** [comment]
ou trouver un header photo avec moins de rouge ;-)

On Thu, May 21, 2015 at 11:15 AM, tonifisler <notifications@github.com>
wrote:

> That Contact Button... My eyes are bleeding.
>
> Shouldn't we switch it to a white background too?
>
> cc/ @guillaumeberry <https://github.com/guillaumeberry> @zufrieden
> <https://github.com/zufrieden>
>
> [image: screen shot 2015-05-21 at 11 13 50]
> <https://cloud.githubusercontent.com/assets/1708450/7745327/ae4a4a0e-ffaa-11e4-9add-f7c486839cf6.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/antistatique/antistatique.net/issues/172>.
>



-- 
---
Marc Friederich
marc@antistatique.net

Antistatique <http://antistatique.net/>
rue de Sébeillon 9b
1004 Lausanne
+41 21 623 63 03
www.antistatique.net
