### ISSUE TITLE
Breadcrumb blog article categories as a dropdown

### ISSUE THREAD

**Issue by tonifisler** [antistatique/antistatique.net#173]
We temporarily display a list of current tags on the article. We want a dropdown with all the other tags if we can... (as with the other pages)

![screen shot 2015-05-21 at 11 15 48](https://cloud.githubusercontent.com/assets/1708450/7745373/f2ed26ae-ffaa-11e4-88ee-bb0388a11682.png)

**Comment by zufrieden** [comment]
Except from the language it's ok for now ;-)

On Thu, May 21, 2015 at 11:18 AM, tonifisler <notifications@github.com>
wrote:

> We temporarily display a list of current tags on the article. We want a
> dropdown with all the other tags if we can... (as with the other pages)
>
> [image: screen shot 2015-05-21 at 11 15 48]
> <https://cloud.githubusercontent.com/assets/1708450/7745373/f2ed26ae-ffaa-11e4-88ee-bb0388a11682.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/antistatique/antistatique.net/issues/173>.
>



-- 
---
Marc Friederich
marc@antistatique.net

Antistatique <http://antistatique.net/>
rue de Sébeillon 9b
1004 Lausanne
+41 21 623 63 03
www.antistatique.net
