### ISSUE TITLE
Teammate enhancements

### ISSUE THREAD

**Issue by tonifisler** [antistatique/antistatique.net#175]
- [x] Add 2 articles
- [x] Add link to all articles
- [x] URLs
- [x] Display only first name in teaser mode
- [x] Add breadcrumb
- [x] Fix `.dark-hero` issue...

**Comment by tonifisler** [comment]
@zufrieden I FIXED IT YEAHHHHHHHH

**Comment by dmrrlc** [comment]
@tonifisler missing breadcrumb translate.. the rest is :+1:
