### ISSUE TITLE
Add skills field to article content type

### ISSUE THREAD

**Issue by tonifisler** [antistatique/antistatique.net#176]

**Comment by zufrieden** [comment]
- [x] Add new field to article content type
- [ ] display in the article detail page

**Comment by tonifisler** [comment]
We need images for all the skills. That way we can display them like this:

![screen shot 2015-08-28 at 16 08 11](https://cloud.githubusercontent.com/assets/1708450/9548133/02d07516-4d9f-11e5-88db-448922b86f68.

:pineapple: @guillaumeberry @sepmil

**Comment by guillaumeberry** [comment]
@tonifisler you mean icons? Displayed vertically, with the tooltip on the right maybe… ;)

**Comment by tonifisler** [comment]
Yeah you're probably right. :wink: 

And yes I mean pretty icons! \o/ :tada:

**Comment by guillaumeberry** [comment]
@tonifisler and last question before starting this: do we have the exhaustive list of those skills?

**Comment by gido** [comment]
It's not a exhaustive lists. And @zufrieden in #285 start a discussion about adding hierarchy in the skills.

**Comment by gido** [comment]
BTW this issue is related (duplicate ?) of #253

**Comment by guillaumeberry** [comment]
almost duplicate @gido !

there is this document : https://docs.google.com/document/d/18nBFvsE3NEkduarh61mrQFHnimpA2mcBKvz498BIvmY/edit

and those spreadsheets :
. https://docs.google.com/spreadsheets/d/1M2lTwE6IATCfI2oV2zvs8cl7bsHhFy79Iicadbt0qUw/edit#gid=0
. https://docs.google.com/spreadsheets/d/1T-9o0L6Z8ev9H1UEvXr3fiz97NADuYQ-a3xoJCJ0W6A/edit#gid=575243592

@zufrieden @gido who is responsible for this list?

**Comment by tonifisler** [comment]
Yes there are duplicates, and we should maybe define more clearly the difference between skills and technologies.

**Comment by tonifisler** [comment]
I'll hide the icons for the time being. We need images ready before we re-add them.

**Comment by tonifisler** [comment]
I will reopen an issue only for the design task.
