### ISSUE TITLE
Blog : authors of article

### ISSUE THREAD

**Issue by nsz** [antistatique/antistatique.net#177]
### What we have
![capture d ecran 2015-05-22 a 15 48 35](https://cloud.githubusercontent.com/assets/1941982/7771868/b6371e36-009a-11e5-827d-48034e647391.png)

### What we want
- [x] Link on the two names
- [x] Separate names with comma

**Comment by nsz** [comment]
And there is two time the same article (the first, one time highlighted and one time standard).
Maybe it's better if it is just one time ?

**Comment by dmrrlc** [comment]
:+1:
