### ISSUE TITLE
Middle content image floats left in portfolios/projects

### ISSUE THREAD

**Issue by sepmil** [antistatique/antistatique.net#178]
Middle content image floats left in portfolios/projects

![capture d ecran 2015-05-26 a 11 41 12 2](https://cloud.githubusercontent.com/assets/6390725/7809661/3ec7a62c-039c-11e5-8003-2ed83a296ed0.png)

**Comment by gido** [comment]
Je pense que c'est mieux !

**Comment by gido** [comment]
@sepmil confirme quand meme

**Comment by sepmil** [comment]
Yes ca marche.

**Comment by sepmil** [comment]
@gido
