### ISSUE TITLE
Add "YOU" as the last member of the team list

### ISSUE THREAD

**Issue by tonifisler** [antistatique/antistatique.net#181]
![screen shot 2015-05-26 at 14 01 43](https://cloud.githubusercontent.com/assets/1708450/7812120/cf485706-03af-11e5-9668-cfcdfc5bd41b.png)

**Comment by zufrieden** [comment]
Apparait à double sur cette page (http://staging.antistatique.net/fr/nous/sommes-une-equipe)
![screen shot 2015-05-29 at 09 59 42](https://cloud.githubusercontent.com/assets/451236/7878700/84645136-05e9-11e5-9a99-7526fb660c35.png)
