### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by dmrrlc** [antistatique/antistatique.net#183]
fr/nous/travaillons missing images
![missing_images](https://cloud.githubusercontent.com/assets/657282/7829820/a1e1ee66-0446-11e5-8b0b-74bb9a114cf3.png)

**Comment by guillaumeberry** [comment]
@zufrieden @tonifisler ils vous manquent les logos ?

**Comment by tonifisler** [comment]
Currently these are *unsplash.com* images. cf https://github.com/antistatique/antistatique.net/issues/179#issuecomment-105493342

Closing.
