### ISSUE TITLE
Fix text field style

### ISSUE THREAD

**Issue by guillaumeberry** [antistatique/antistatique.net#187]
- [x] White background
- [ ] onFocus : border : midnight-blue + grrrey glow

**Comment by guillaumeberry** [comment]
![text-field](https://cloud.githubusercontent.com/assets/1800253/7859401/fe7c7452-0540-11e5-8e26-6953fb4cad57.png)

**Comment by dmrrlc** [comment]
much better :+1:

**Comment by guillaumeberry** [comment]
onFocus is still blue for me :disappointed:
