### ISSUE TITLE
Fix z-index of user-profile header

### ISSUE THREAD

**Issue by tonifisler** [antistatique/antistatique.net#191]
![screen shot 2015-05-29 at 13 54 29](https://cloud.githubusercontent.com/assets/1708450/7882088/498f1016-060a-11e5-8fdd-89cc10608c5e.png)

**Comment by gido** [comment]
![screen shot 2015-05-29 at 16 14 02](https://cloud.githubusercontent.com/assets/101859/7884393/cf6d20c0-061d-11e5-8144-0074e09d2e0d.png)
![screen shot 2015-05-29 at 16 15 25](https://cloud.githubusercontent.com/assets/101859/7884425/04071624-061e-11e5-9c23-d28486441d65.png)

@tonifisler still buggy

**Comment by tonifisler** [comment]
Yep @gido, no commit to fix this yet :wink:

**Comment by zufrieden** [comment]
Can't we use a select option for that guys ? and style the normal effect.
Yes we can ! http://www.hanseri.no/a-closer-look-at-the-select-element/
