### ISSUE TITLE
Fix hover underline of YOU element in team view

### ISSUE THREAD

**Issue by tonifisler** [antistatique/antistatique.net#192]
![screen shot 2015-05-29 at 14 35 44](https://cloud.githubusercontent.com/assets/1708450/7882652/12162466-0610-11e5-9c75-247fab0d4200.png)

**Comment by gido** [comment]
![screen shot 2015-05-29 at 16 09 55](https://cloud.githubusercontent.com/assets/101859/7884321/2c891a1c-061d-11e5-86c5-2ee18bd3c8cf.png)

Il y a pas de soulignement

**Comment by gido** [comment]
:+1: OK now
