### ISSUE TITLE
Dismissible alert on blog pages

### ISSUE THREAD

**Issue by guillaumeberry** [antistatique/antistatique.net#194]
Can we put a dismissible alert to explain that our articles are only available in french?

**Comment by tonifisler** [comment]
On it, boss! :boar:

**Comment by guillaumeberry** [comment]
Ok. I must be blind. Don't see shit! :black_circle: . :black_circle:

**Comment by tonifisler** [comment]
Validated in Hipchat :eyeglasses:

**Comment by guillaumeberry** [comment]
Yeah! :+1:
