### ISSUE TITLE
Improve maintenance page

### ISSUE THREAD

**Issue by gido** [antistatique/antistatique.net#197]
![screen shot 2015-05-29 at 16 24 52](https://cloud.githubusercontent.com/assets/101859/7884588/45c7d156-061f-11e5-9d72-05b28daec24a.png)

**Comment by gido** [comment]
+ change sitename

**Comment by tonifisler** [comment]
![screen shot 2015-09-03 at 11 33 52](https://cloud.githubusercontent.com/assets/1708450/9655187/b0b89eda-522f-11e5-83d1-46ed3dc7ea0e.png)
