### ISSUE TITLE
Homepage on Android is not perfect

### ISSUE THREAD

**Issue by gido** [antistatique/antistatique.net#199]
![screenshot_2015-05-29-16-27-54](https://cloud.githubusercontent.com/assets/101859/7884985/a822f022-0621-11e5-8005-438d3d4a291e.png)

Maybe related to #196 ?

**Comment by tonifisler** [comment]
We'll look at these weird offsets above and below once @guillaumeberry has changed the cover image ;)

**Comment by zufrieden** [comment]
somehow linked to #202

**Comment by tonifisler** [comment]
Is this still a problem @gido? I fixed pretty much everything in #202, so I need confirmation. :wink:

**Comment by gido** [comment]
:+1: Fixed!
