### ISSUE TITLE
Article

### ISSUE THREAD

**Issue by tonifisler** [antistatique/antistatique.net#2]
### Fields

| Field | Type | Full | Teaser | Required | Comment |
|-------|------|:----:|:------:|:--------:|---------|
| title | text | ✔︎ | ✔︎ | Yes | max 128 caractères |
| hero-image | image | ✔︎ | ✔︎ | Yes | paysage - min 1500 px de large - random pattern si pas d'upload ou HEX |
| date | date | ✔︎ | ✔︎ | Yes | auto (publication date) format 26 janvier 2015 / January, 26th 2015 ou 3 days ago pour le teaser |
| body | body + excerpt | ✔︎ | | Yes |
| images | image (multiple) | ✔︎ | | | —> Images to insert in body |
| category | Term Reference (max 3) | ✔︎ | ✔︎ | Yes | basé sur la liste des catégories (read, listen, talk, socialize, etc.) |
| author | default option | ✔︎ | ✔︎ | Yes | |
| promoted to front page | default option | | | Yes | |

### To also be displayed

| Thing | Full | Teaser | Comment |
|-------|:----:|:------:|---------|
| Comment count | ✔︎ | ✔︎ | based on Disqus |
| Related articles | ✔︎ | | views to display the different  |

**Comment by zufrieden** [comment]
No paragraph™ for article

**Comment by guillaumeberry** [comment]
@zufrieden only rich text editor?

**Comment by zufrieden** [comment]
yes @guillaumeberry

**Comment by tonifisler** [comment]
@guillaumeberry Yes for the blog article this makes more sense. We will only apply some css styling on the body.

**Comment by zufrieden** [comment]
@gido argued with sementics/meanings and future needs of exportation.

**Comment by guillaumeberry** [comment]
Ok, deal!

**Comment by zufrieden** [comment]
This tool is a chat ;-)

**Comment by guillaumeberry** [comment]
:cat: Meow!

**Comment by tonifisler** [comment]
:shipit:

**Comment by tonifisler** [comment]
- [ ] Replace title field with the title module. Otherwise it's not translatable.
- [ ] Not sure about Checkbox for categories. We can't add a new one on the fly? Otherwise display as select list and apply Chosen
- [ ] Display co-author as a Select List and apply Chosen
- [ ] Add insert module to images field (it's weird that it's not below the body in this case)
- [ ] Disable menu? Articles will never be directly in a menu.
- [ ] enable field translation
- [ ] disable promoted to frontpage by default
- [ ] create revision by default
