### ISSUE TITLE
General Reponsive Enhancements

### ISSUE THREAD

**Issue by tonifisler** [antistatique/antistatique.net#202]
Some tests need to be done on tablet and mobile! :)

**Comment by nsz** [comment]
- [ ] "nous socialisons" add some trouble on mobile (iphone 7.1.2 - safari)
![img_0593](https://cloud.githubusercontent.com/assets/1941982/7931348/4c694316-0910-11e5-824b-8dceae9b042f.jpg)
- [ ] menu on mobile, "FR" and "EN" are not aligned
![img_0594 1](https://cloud.githubusercontent.com/assets/1941982/7931495/6b48a974-0911-11e5-82da-7a58efda8516.jpg)
- [ ] newsletter on mobile : maybe "s'inscrire" should be under the field for more space ?
![img_0595 1](https://cloud.githubusercontent.com/assets/1941982/7931545/ca1b97e0-0911-11e5-887c-1a47b5069ca3.jpg)

**Comment by nsz** [comment]
### Tablette Ipad - safari - français
- [ ] The pictures aren't round (the borders are cut) or sometimes there are not here. 
![img_0079](https://cloud.githubusercontent.com/assets/1941982/7932462/bd9be4b4-0918-11e5-98dc-f9b65337550f.jpg)

![img_0081](https://cloud.githubusercontent.com/assets/1941982/7932398/56bf88c2-0918-11e5-955f-6c42bebbfb65.jpg)

- [ ] On the page "nous" there is french and english on the french version.
![img_0080](https://cloud.githubusercontent.com/assets/1941982/7932432/844e54d0-0918-11e5-8b64-197a8a998e74.jpg)

- [ ] The title of some project are too long (or the font too big?)
![img_0082](https://cloud.githubusercontent.com/assets/1941982/7932448/a0a179e6-0918-11e5-8a55-081a5dbd532b.jpg)

- [ ] The logo is black and we can't click on the menu
![img_0076](https://cloud.githubusercontent.com/assets/1941982/7932475/d3cfe3fc-0918-11e5-85ba-0722d49ded0c.jpg)

- [ ] There are some troubles with the "socialisons" part
![img_0077](https://cloud.githubusercontent.com/assets/1941982/7932497/eb5d38da-0918-11e5-971b-01d76724d187.jpg)

- [ ] the logo "antistatique" is not well displayed on the footer
![img_0078](https://cloud.githubusercontent.com/assets/1941982/7932518/131e44f4-0919-11e5-893b-22828f1a8bc5.jpg)

**Comment by nsz** [comment]
### Tablette nexus chrome

- [ ] the project are not well displayed : the title are too big compared to the picture
![screenshot_2015-06-02-11-30-55](https://cloud.githubusercontent.com/assets/1941982/7932938/e342380a-091b-11e5-98d7-8f284f9d14bc.png) 

### Tablette nexus firefox

- [ ] there aren't enough space between the picture
![screenshot_2015-06-02-11-27-59](https://cloud.githubusercontent.com/assets/1941982/7932963/0d6d9a66-091c-11e5-88f3-6e974ed3aa1e.png)

- [ ] in portrait and landscape, projects are not well displayed. They are not all the same size or the title extends beyond the image
![screenshot_2015-06-02-11-28-27](https://cloud.githubusercontent.com/assets/1941982/7933018/67294258-091c-11e5-9933-8e02a7df05b4.png)
![screenshot_2015-06-02-11-29-16](https://cloud.githubusercontent.com/assets/1941982/7933017/67291e54-091c-11e5-9dde-39075c508990.png)

**Comment by nsz** [comment]
### mobile samsung android 

- [ ] the logo is under the address, we can not read it
![screenshot_2015-06-02-11-44-50](https://cloud.githubusercontent.com/assets/1941982/7933237/1aabba94-091e-11e5-9650-0851804c3f34.png)

- [ ] the display of the profile picture does not work
![screenshot_2015-06-02-11-47-24](https://cloud.githubusercontent.com/assets/1941982/7933246/29c2bdf2-091e-11e5-9cbf-538ff49403b2.png)

**Comment by tonifisler** [comment]
> On the page "nous" there is french and english on the french version.

Couldn't reproduce

**Comment by tonifisler** [comment]
Good people, gather round! :horse: :postal_horn: :european_castle:  

*And he then shouted*:
#### – I think all these bugs are fixed.

**Comment by zufrieden** [comment]
:+1:
