### ISSUE TITLE
Les icônes ne s'affichent pas sur Chrome

### ISSUE THREAD

**Issue by eevy** [antistatique/antistatique.net#207]

**Comment by zufrieden** [comment]
![screen shot 2015-06-03 at 18 12 24](https://cloud.githubusercontent.com/assets/451236/7965184/257269c4-0a1c-11e5-9afb-330f727fd14f.png)
![screen shot 2015-06-03 at 18 12 38](https://cloud.githubusercontent.com/assets/451236/7965183/25710e4e-0a1c-11e5-99f1-041e121ae8d7.png)
