### ISSUE TITLE
sitemap xml, check how it looks

### ISSUE THREAD

**Issue by zufrieden** [antistatique/antistatique.net#210]
- [x] Articles FR
- [x] Basic page FR/EN
- [x] Team mate
- [x] Projects
- [ ] Check multilangual settings

**Comment by gido** [comment]
Install another module https://www.drupal.org/project/xmlsitemap ?

**Comment by tonifisler** [comment]
Module added in 04c6b00.

**Comment by gido** [comment]
Well, the sitemap module is installed but not completely configured.

**Comment by gido** [comment]
Added basic page and project to sitemap

**Comment by dmrrlc** [comment]
http://antistatique.net/sitemap.xml there are unpublished nodes in the sitemap like 
- http://antistatique.net/fr/meet/admin
- http://antistatique.net/fr/meet/cedric
- http://antistatique.net/fr/meet/simon

**Comment by gido** [comment]
This can be fixed by editing the user and choosing "Sitemap XML > Excluded" option:
![screen shot 2015-08-28 at 09 18 15](https://cloud.githubusercontent.com/assets/101859/9541220/6badb014-4d66-11e5-93b5-f60e23e53918.png)

Should be done, now.

**Comment by tonifisler** [comment]
@gido Can we automate that in any way?

**Comment by gido** [comment]
Certainly. But is it priority ?

By default "non-published" nodes are not in the sitemap. Users have is own logic ("Currently working", etc.) and we can manage this manually.

**Comment by tonifisler** [comment]
Ok so I'll add a note about this needed change on the "Currently working" checkbox.
