### ISSUE TITLE
Update Banner Portfolio Athena

### ISSUE THREAD

**Issue by eevy** [antistatique/antistatique.net#217]

**Comment by nsz** [comment]
Si jamais l'image en meilleure résolution se trouve ici : afp://hal9000._afpovertcp._tcp.local/Projects/001_antistatique_communication/Communication/2_Blog/public-domain-images-archive-high-quality-resolution-free-download-splitshire-0008.jpg

**Comment by guillaumeberry** [comment]
Done!
