### ISSUE TITLE
Projects tiles enhancements

### ISSUE THREAD

**Issue by tonifisler** [antistatique/antistatique.net#218]
In order to fix the reallllllly ugly projects tiles issue with those thousand words titles:

![screen shot 2015-06-09 at 14 12 43](https://cloud.githubusercontent.com/assets/1708450/8057446/a104f734-0eb1-11e5-9d8a-6958af161236.png)

, I suggest this:

![screen shot 2015-06-09 at 11 15 38](https://cloud.githubusercontent.com/assets/1708450/8057456/b7a2d13c-0eb1-11e5-8eef-f9c076e00029.png)

So we basically add a new subtitle field. And THIS FIELD ONLY can then be longer. It is displayed on the full mode only. Wattayathink @guillaumeberry @zufrieden

**Comment by zufrieden** [comment]
Bof pas fan.
Je propose plutôt de raccourcir le titre. Je me ferais violence ;-) promis.
C'est moi l'auteur des gros titres.

On Tue, Jun 9, 2015 at 2:18 PM, tonifisler <notifications@github.com> wrote:

> In order to fix the reallllllly ugly projects tiles issue with those
> thousand words titles:
>
> [image: screen shot 2015-06-09 at 14 12 43]
> <https://cloud.githubusercontent.com/assets/1708450/8057446/a104f734-0eb1-11e5-9d8a-6958af161236.png>
>
> , I suggest this:
>
> [image: screen shot 2015-06-09 at 11 15 38]
> <https://cloud.githubusercontent.com/assets/1708450/8057456/b7a2d13c-0eb1-11e5-8eef-f9c076e00029.png>
>
> So we basically add a new subtitle field. And THIS FIELD ONLY can then be
> longer. It is displayed on the full mode only. Wattayathink
> @guillaumeberry <https://github.com/guillaumeberry> @zufrieden
> <https://github.com/zufrieden>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/antistatique/antistatique.net/issues/218>.
>



-- 
---
Marc Friederich
marc@antistatique.net

Antistatique <http://antistatique.net/>
rue de Sébeillon 9b
1004 Lausanne
+41 21 623 63 03
www.antistatique.net

**Comment by tonifisler** [comment]
Je sais bien que tu es le coupable! Bouh! Hahaha

Alors c'est parfait si tu proposes finalement de raccourcir les titres. C'est ce que je voulais. :+1: :stuck_out_tongue_closed_eyes:

**Comment by zufrieden** [comment]
Arf. Owned

**Comment by tonifisler** [comment]
TODO: shorten the longest titles.

**Comment by tonifisler** [comment]
Done in staging.
