### ISSUE TITLE
SVG upload not working anymore

### ISSUE THREAD

**Issue by guillaumeberry** [antistatique/antistatique.net#219]
Cannot upload svg files in backend. :(

Message:
“The specified file antistatique.svg could not be uploaded. Only files with the following extensions are allowed: .”

**Comment by tonifisler** [comment]
Okay this is because we removed the media module #198. Now a SVG can't be uploaded to an image field, we have to use a file field. I'll change this everywhere, we'll have to re-upload the missing SVGs.

**Comment by guillaumeberry** [comment]
Yay! Works just ﬁne!
