### ISSUE TITLE
Improve contact form on mobile

### ISSUE THREAD

**Issue by tonifisler** [antistatique/antistatique.net#221]
**iPhone 4s**:

![ios simulator screen shot 11 jun 2015 10 38 54](https://cloud.githubusercontent.com/assets/1708450/8103099/179e1f04-1026-11e5-8719-06070c0453a7.png)

**Comment by guillaumeberry** [comment]
Will work on that!
- Labels
- Styles

**Comment by gido** [comment]
While we are talking about the Contact Form.

Is it me or it's difficult to find our email on the contact page: http://antistatique.net/fr/nous/travaillons/avec/vous ?

Because at the moment, all contact request look like a copy paste email...

**Comment by zufrieden** [comment]
+1 to display hello@antistatique.net bigger and in a better place. And
change Contact form title ;-)

On Mon, Jul 13, 2015 at 11:12 AM, Gilles Doge <notifications@github.com>
wrote:

> While we are talking about the Contact Form.
>
> Is it me or it's difficult to find our email on the contact page:
> http://antistatique.net/fr/nous/travaillons/avec/vous ?
>
> Because at the moment, all contact request look like a copy paste email...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/antistatique/antistatique.net/issues/221#issuecomment-120861579>
> .
>



-- 
---
Marc Friederich
marc@antistatique.net

Antistatique <http://antistatique.net/>
rue de Sébeillon 9b
1004 Lausanne
+41 21 623 63 03
www.antistatique.net

**Comment by gido** [comment]
> change Contact form title
"The [Fabulous/Banal/Useless](hello@antistatique.net) Contact form" ?

or

"Fill this form and make some happyness (someone in the team will receive a
free icecream/pizza/burger)"



*--Antistatique*
Gilles Doge
+41 21 623 63 03
+41 78 810 67 66
www.antistatique.net

**Comment by gido** [comment]
![screen shot 2015-07-22 at 18 55 42](https://cloud.githubusercontent.com/assets/101859/8831531/4a398c8a-30a3-11e5-9810-fb12bb367dca.png)
Si ça vous plait pas, vous pouvez changer ;)

**Comment by guillaumeberry** [comment]
One step further… :+1: 

We need a bigger font size (why not the same one as the phone number?)
I still need to work on this form and we need to change the form title…

**Comment by guillaumeberry** [comment]
While I'm at it…
![form](https://cloud.githubusercontent.com/assets/1800253/9549835/521fdfc2-4da8-11e5-8dda-9cfd6f6aafbf.png)

**Comment by tonifisler** [comment]
### iPhone 6:
![simulator screen shot 03 sep 2015 11 37 11](https://cloud.githubusercontent.com/assets/1708450/9655426/2fdd9c14-5231-11e5-985a-521310b3b8ea.png)


### iPhone 4S:
![simulator screen shot 03 sep 2015 11 39 56](https://cloud.githubusercontent.com/assets/1708450/9655418/23265448-5231-11e5-856b-ca69af411763.png)
