### ISSUE TITLE
We socialize on mobile

### ISSUE THREAD

**Issue by guillaumeberry** [antistatique/antistatique.net#222]
What do you think @tonifisler @zufrieden ?
![buenavista-social-club-mobile](https://cloud.githubusercontent.com/assets/1800253/8103401/7d62214e-1028-11e5-9518-a5225da7c722.png)

**Comment by tonifisler** [comment]
First one :+1:

**Comment by zufrieden** [comment]
First too

On Thu, Jun 11, 2015 at 10:57 AM, tonifisler <notifications@github.com>
wrote:

> First one [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/antistatique/antistatique.net/issues/222#issuecomment-111048812>
> .
>



-- 
---
Marc Friederich
marc@antistatique.net

Antistatique <http://antistatique.net/>
rue de Sébeillon 9b
1004 Lausanne
+41 21 623 63 03
www.antistatique.net

**Comment by tonifisler** [comment]
Done, review please!

**Comment by guillaumeberry** [comment]
All good expect the font-size: should be standard <p> size, not 14px tiny thing @tonifisler

**Comment by guillaumeberry** [comment]
Pas si vite @tonifisler !
![hophophop](https://cloud.githubusercontent.com/assets/1800253/8131155/9f83e672-1118-11e5-9f9e-907ab35eed4a.png)

**Comment by tonifisler** [comment]
Link or didn't happen. :)

**Comment by tonifisler** [comment]
So linked to #228. Closing.
