### ISSUE TITLE
[suggestion] Products - open in new tab

### ISSUE THREAD

**Issue by dmrrlc** [antistatique/antistatique.net#226]
Products links should be opened in a new tab as there is no back button then

![image](https://cloud.githubusercontent.com/assets/657282/8130950/3cd72b3e-1117-11e5-9932-fcf7e33acbef.png)
http://staging.antistatique.net/fr/nous

**Comment by tonifisler** [comment]
:+1:

**Comment by gido** [comment]
Done in staging.
