### ISSUE TITLE
Translate products section on /fr/we page

### ISSUE THREAD

**Issue by zufrieden** [antistatique/antistatique.net#227]

**Comment by tonifisler** [comment]
Done in staging.

**Comment by Saniha** [comment]
Reviewed!
One change. 

*Nos Produits*
De temps en temps, nous sommes notre propre client, nous mettons en marche nos idées et nous créons de nouvelles choses. C'est aussi pour nous l'occasion de devnenir meilleurs dans ce que nous savons faire!

--> change "devnenir" in "devenir"

**Comment by Saniha** [comment]
(I can't edit the above section)

**Comment by tonifisler** [comment]
Done in staging.
