### ISSUE TITLE
Wording

### ISSUE THREAD

**Issue by Saniha** [antistatique/antistatique.net#236]
http://staging.antistatique.net/fr/nous/faisons/de-la-strategie-digitale

"À la base de tout projet, la stratégie définit les moyens d’atteindre vos objectifs. Nous vous proposons des solutions innovantes et originales pour retenir l'attention de votre public-cible. Une idée forte et innovante, la connaissance du web et les fondamentaux du marketing représentent les 3 piliers de notre méthode"

May I delete one of the 2 "innovant" word?

**Comment by Saniha** [comment]
(same in english)

**Comment by tonifisler** [comment]
Done in staging.
