### ISSUE TITLE
Wording

### ISSUE THREAD

**Issue by Saniha** [antistatique/antistatique.net#238]
http://staging.antistatique.net/fr/nous/travaillons/avec

A la place de "nous faisons avec nos clients" ce qui fait sacrément suisse allemand, je mettrais "nous faisons des super projets avec nos clients"

Qu'en dites-vous? @zufrieden @tonifisler ?

**Comment by Saniha** [comment]
(et ça a un côté un peu sexe aussi...)

**Comment by Saniha** [comment]
(ou scato...)

**Comment by tonifisler** [comment]
:dancers: vendu! :laughing:

**Comment by tonifisler** [comment]
Done in staging.
