### ISSUE TITLE
Job titles

### ISSUE THREAD

**Issue by Saniha** [antistatique/antistatique.net#239]
http://staging.antistatique.net/fr/nous/sommes-une-equipe

Attention les titres ne sont pas tous cohérents: Ludo a Project Manager, J'ai Web project Manager. Marc n'a pas "web" devant son "Software", Luc et Gilles l'ont. 
Aussi: pas de traduction française des termes.

**Comment by tonifisler** [comment]
@Saniha Les termes ne sont pas traduits, non. C'est un choix qu'on avait fait au moment du renouvellement des cartes de visites également. We are so bilingue. :us: 

Pour ce qui est des **Web [...]** c'est au bon vouloir de chacun, me semble-t-il. @zufrieden, on norme ça?

**Comment by Saniha** [comment]
Okay okay! hehe :)

Par contre les termes doivent avoir une cohérence je trouve...

**Comment by zufrieden** [comment]
Clairement pas du 1.0 ;-)
