### ISSUE TITLE
Blog largeur des post

### ISSUE THREAD

**Issue by zufrieden** [antistatique/antistatique.net#241]
8 col au lieu de 6
- [x] Changer les col-md
- [x] Changer le format d'image du display mode featured

![screenshot 2015-06-15 14 23 43](https://cloud.githubusercontent.com/assets/451236/8159765/415ff1c2-136a-11e5-8abf-0edce28d635e.png)
![screenshot 2015-06-15 14 23 54](https://cloud.githubusercontent.com/assets/451236/8159764/415d918e-136a-11e5-8a30-0c7f0cdc9798.png)

**Comment by tonifisler** [comment]
Ready for review

**Comment by zufrieden** [comment]
not ok yet
