### ISSUE TITLE
Scroll customers too long

### ISSUE THREAD

**Issue by dmrrlc** [antistatique/antistatique.net#246]
Should we place them it 2 cols?
![screenshot_2015-06-16-13-52-23](https://cloud.githubusercontent.com/assets/657282/8182462/e67ec794-142f-11e5-90b6-6a73e3de53b6.png)

**Comment by guillaumeberry** [comment]
- [ ] Reduce line-height
- [ ] Maybe 2 columns?

@zufrieden @tonifisler
