### ISSUE TITLE
Translation workflow

### ISSUE THREAD

**Issue by tonifisler** [antistatique/antistatique.net#252]
These are some things I noticed not working and we need to do:

- Copier Paragraphs content lors de la création de la traduction (à voir ce qui est possible de faire avec replicate_paragraphs) (see issue: https://www.drupal.org/node/2452675)
- hide unpublished translated content (checkbox currently not working) (see issue: https://www.drupal.org/node/1762064)
- faire un petit tuto drupal pour Katy

**Comment by zufrieden** [comment]
- [ ] Hide "Ready for translation" in display mode project content type
