### ISSUE TITLE
[article] Fix WordPress Smilies in imported blog post

### ISSUE THREAD

**Issue by gido** [antistatique/antistatique.net#256]
http://antistatique.net/fr/nous/bloggons/2015/02/16/dpm-uk-conf/#comment-1858357367
http://antistatique.net/blog/wp-includes/images/smilies/icon_smile.gif -> 404 but should return a 200

**Comment by Yago** [comment]
@gido Du coup on pourrait installer [Emojify.js](https://github.com/Ranks/emojify.js) pour utiliser les codes standards (`:wink:`) ?

**Comment by Yago** [comment]
## Emojis in content

@antistatique/antistatique Now, we can do something like : 

<img width="634" alt="capture d ecran 2015-07-31 a 14 07 10" src="https://cloud.githubusercontent.com/assets/2025924/9007045/fb21be82-378d-11e5-8bf8-3d1991a3347f.png">

:point_right: by using [emoji's code](http://www.emoji-cheat-sheet.com/) or classic smiley (":)", ";)", ":D", ...)

**Comment by tonifisler** [comment]
:shipit:
