### ISSUE TITLE
Notice: Undefined index: domain in disqus_node_view()

### ISSUE THREAD

**Issue by gido** [antistatique/antistatique.net#258]
The Disqus project is [not](https://www.drupal.org/node/2502077) [so](https://www.drupal.org/node/2499753) [stable](https://www.drupal.org/node/2508561).

https://www.drupal.org/node/2499753

**Comment by tonifisler** [comment]
@gido I had this problem for the EpicGameJam. My solution is to stick to v7.x-1.10.

**Comment by dmrrlc** [comment]
We will wait for an update of the Disqus module
