### ISSUE TITLE
Define English as default when exporting the features with Drush

### ISSUE THREAD

**Issue by gido** [antistatique/antistatique.net#260]
See #257

**Comment by tonifisler** [comment]
Looking into this now, as it annoys the hell out of me. :rage: 

See: https://www.drupal.org/node/874760

Seems it will be fixed once https://www.drupal.org/node/1988252 is merged. I'll apply the patch for now.

**Comment by zufrieden** [comment]
Good

On Mon, Jul 27, 2015 at 8:45 AM, Toni Fisler <notifications@github.com>
wrote:

> Looking into this now, as it annoys the hell out of me. [image: :rage:]
>
> See: https://www.drupal.org/node/874760
>
> Seems it will be fixed once https://www.drupal.org/node/1988252 is
> merged. I'll apply the patch for now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/antistatique/antistatique.net/issues/260#issuecomment-125105153>
> .
>



-- 
---
Marc Friederich
marc@antistatique.net

Antistatique <http://antistatique.net/>
rue de Sébeillon 9b
1004 Lausanne
+41 21 623 63 03
www.antistatique.net

**Comment by tonifisler** [comment]
Ok it doesn't work on my machine... Is it ok on your sides?

**Comment by gido** [comment]
@tonifisler pls do this into a branch

**Comment by tonifisler** [comment]
This may have been fixed with this: https://www.drupal.org/node/1988252

**Comment by tonifisler** [comment]
We need to check if this is still an issue now. I might have seen some weird translations in my features, but it could be the last time this happens.
