### ISSUE TITLE
Google is indexing https pages - Install a SSL Certificate

### ISSUE THREAD

**Issue by dmrrlc** [antistatique/antistatique.net#261]
![image](https://cloud.githubusercontent.com/assets/657282/8574698/61c28070-2598-11e5-8c02-f6f4e10653d6.png)

https://antistatique.net/fr/job/web-developer

**Comment by gido** [comment]
and ?

**Comment by gido** [comment]
So the issue is that we don't have a SSL Certificate configured for this domain.

**Comment by zufrieden** [comment]
Without a proper certificate most user will freak out and go somewhere safer

**Comment by dmrrlc** [comment]
I added the certificate through the alwaysdata admin. Should I buy a static IP as well?

**Comment by dmrrlc** [comment]
@gido

**Comment by gido** [comment]
IP Already done

Antistatique
Gilles Doge

**Comment by gido** [comment]
Done.
