### ISSUE TITLE
[font] FF-Dagny-Web-Pro don't support á ?

### ISSUE THREAD

**Issue by gido** [antistatique/antistatique.net#272]
Reported by user:
---

Your "ff-dagny-web-pro" font does not support the google auto-translation to
spanish due to the 'á' character is not included. please, review the

You could check it out at...
http://antistatique.net/fr/nous/travaillons/avec/tehran-watch
...title. It's translated as "Teherán reloj" but the "á" seems different
than the other chars.

Try to re-build the font-face. Maybe it should work fine.

Bye!

**Comment by guillaumeberry** [comment]
Done
