### ISSUE TITLE
Design et intégration du numero de téléphone de Genève

### ISSUE THREAD

**Issue by gido** [antistatique/antistatique.net#276]
Faut revoir cette page http://antistatique.net/fr/nous/travaillons/avec/vous pour intégrer notre nouveau numero de téléphone.

**Comment by gido** [comment]
@sepmil design:
![capture d ecran 2015-07-31 a 11 46 35](https://cloud.githubusercontent.com/assets/101859/9021355/b6031236-383e-11e5-8f91-5327a3a30778.png)

**Comment by tonifisler** [comment]
Done in prod: http://antistatique.net/fr/nous/travaillons/avec/vous

**Comment by gido** [comment]
:+1:
