### ISSUE TITLE
Hero-image is required -> Prepare default image

### ISSUE THREAD

**Issue by gido** [antistatique/antistatique.net#28]
Because:
![screen shot 2015-03-13 at 21 00 31](https://cloud.githubusercontent.com/assets/101859/6646318/056473c2-c9c4-11e4-9643-ee4d323db464.png)

**Comment by gido** [comment]
> The image is too small; the minimum dimensions are 1500x600 pixels.

Like this you know... Fuck, this will kill frontend perf (a bit :smiling_imp: ) !

**Comment by guillaumeberry** [comment]
Mnimum dimensions are 1500x844: to respect the desktop display ratio! :wink:

**Comment by guillaumeberry** [comment]
What can we prepare for default image:
A— A folder somewhere for people to pick and choose, then upload
B— Feed the backend with a bunch of thumbnails and people pick one (radio button thumbnails component)
C— Randomize the default image if no images has been uploaded

**Comment by mariontame** [comment]
Images : afp://hal9000._afpovertcp._tcp.local/Projects/001_antistatique_communication/Communication/13_Photos/Site  2015/
