### ISSUE TITLE
CSS: <h4> styling

### ISSUE THREAD

**Issue by gido** [antistatique/antistatique.net#297]
First question: Can we use `<h4>` in our blog post ?

If yes, we need to design it because this is weird (`<h4>` looks bigger than `<h3>`):
![screen shot 2015-09-29 at 13 07 19](https://cloud.githubusercontent.com/assets/101859/10162387/1e98d304-66ab-11e5-9ebe-5614028f590a.png)

**Comment by tonifisler** [comment]
It was designed that way (http://antistatique.net/styleguide/):

<img width="619" alt="screen shot 2015-09-30 at 08 01 30" src="https://cloud.githubusercontent.com/assets/1708450/10185549/82c44b1c-6749-11e5-9105-d154dfa9336c.png">

Maybe we could reduce to `font-size: 32px;` on desktop (and its equivalent on other media queries).

**Comment by gido** [comment]
@guillaumeberry are you OK to reduce the font-size ?

**Comment by guillaumeberry** [comment]
@gido @tonifisler I am. I thought that the magic-responsive-calculation that Marc did, was Ok. But I guess we need those tiny adjustments! :smiley:

**Comment by zufrieden** [comment]
pushed on dev

**Comment by gido** [comment]
:+1:
