### ISSUE TITLE
Teammate

### ISSUE THREAD

**Issue by tonifisler** [antistatique/antistatique.net#3]
### Fields

| Field | Type | Full | Teaser | Tiny | Required | Comment |
|-------|------|:----:|:------:|:----:|:--------:|---------|
| First Name | Text | ✔ | ✔ | ✔ | Yes | |
| Last Name | Text | ✔ | ✔ | | Yes | |
| Job Title | Text | ✔ | ✔ | | Yes | |
| Email | Email | ✔ | | | Yes | |
| Hero Image | Image | ✔ | | | Yes | |
| Avatar Image | Image | ✔ | ✔ | ✔ | Yes | |
| Body + Excerpt | Body | ✔ | | | Yes | Biography (short) |
| Images | Image (4) | ✔ | | | Yes | see comment 1 below |
| Links | List text (unlimited) | ✔ | | | | List with service links (Twitter, Github...)|
| Ping Pong Ranking | Integer | ✔ | | | | |
| Currently Working | boolean | | | | | If not, will not be displayed, but will stay as article author |
| Stick at the top | default option | | | | | Alberto + Marc + Gilles at the top! (cf comment 2 below) |

### Comments

- **1** – First image will be formatted as a big one, two next small Instagram-style, and the fourth is again bigger. [see example](https://projects.invisionapp.com/d/main#/console/1442313/54654724/preview)
- **2** – We could create a custom ordering view (cf AISTS) to set the order and have more control over this (Juniors at the end, same jobs together)

### To also be displayed

| Thing | Full | Teaser | Comment |
|-------|:----:|:------:|---------|
| Related Projects | ✔︎ | | Based on Main Job |
| All the teammates | ✔ | | With current highlighted |

**Comment by zufrieden** [comment]
Option B for me.
Related project curated by the teammate.
We could also display his best articles this way ? @tonifisler WDYT ?

**Comment by tonifisler** [comment]
Mmmh can become obsolete after a while if we forget to update with our new best articles.

**Comment by zufrieden** [comment]
Ok. So we'll automatize that later on ... most commented article or something alike ;-)
- So we stay with related project. I'll add that

**Comment by tonifisler** [comment]
:+1:

**Comment by zufrieden** [comment]
Well I need project content type first ;-)

**Comment by gido** [comment]
@zufrieden review:

 1. "job_title" -> "Job title" dans l'interface
 2. Links: il y a un moyen de savoir de quel type de link il s'agit ? twitter, stackoverflow, linkedin, ... ?
 3. Currently working est demandé lors de l'ajout d'un utilisateur et dans l'édition d'un profil utilisateur. Un help message sera une bonne idée de savoir de quoi il s'agit et quel sont les effets.
 4. Renommer "Picture" par "Avatar Image" ?
 5. Stick at the top, comment on configure ?

**Comment by guillaumeberry** [comment]
One concern regarding people's links:
in the mockups, I've put “gendered” links (see screenshot).

![links](https://cloud.githubusercontent.com/assets/1800253/6651742/398c27c8-ca53-11e4-83ec-541dac9db213.png)

**And there's no gender content type.**

How do we solve that:
- [ ] We put <Firstname>'s blog posts
- [ ] We add a gender content type (and use it to display the gender equity level :p somewhere in a data page)

**Comment by tonifisler** [comment]
Could be a fun idea for a data page yes. And we have to have a custom field for this info or find another link label. @zufrieden?

Damn this english way of writing "his/her"! :dancer:

**Comment by zufrieden** [comment]
Generaly ok ... We'll create specific issue
