### ISSUE TITLE
Update "We are hiring" page to display correct info about spontaneous applications in case no job offered

### ISSUE THREAD

**Issue by guillaumeberry** [antistatique/antistatique.net#302]
Can we display the “We are hiring” badge ONLY when there are job openings? That could be very disappointing to click on it and end up with a page without job offers. We also accept spontaneous application, so we may consider a different label as a work-around… What do you think?

**Comment by tonifisler** [comment]
:+1:

**Comment by gido** [comment]
We are talking about this, right ?

![screen shot 2015-12-04 at 15 22 20](https://cloud.githubusercontent.com/assets/101859/11591811/d560236c-9a9a-11e5-8510-d2beafbc8958.png)

If yes, I'm :-1: and we can work on the text of the page http://antistatique.net/fr/nous/embauchons when there is no open job

**Comment by tonifisler** [comment]
Closing this. I think it's fixed.
