### ISSUE TITLE
BLOCKING – Be sure that `librairies` module is enabled

### ISSUE THREAD

**Issue by gido** [antistatique/antistatique.net#325]
I quickly enabled it on production as a hotfix to an issue blocking the edition of an article.

**Comment by Sudei** [comment]
This issue is still live or already resolved ?

**Comment by gido** [comment]
looks like resolved.

**Comment by tonifisler** [comment]
Nope, can't add an article on the staging.

`Fatal error: Call to undefined function libraries_detect() in /home/antistatique/www/staging.antistatique.net/releases/20160810144839/drupal/sites/all/modules/ace_editor/ace_editor.module on line 618`

**Blocking** must be fixed before deploying the next version

**Comment by gido** [comment]
@tonifisler so you have to enable the module, export as a feature and this is it.

**Comment by Sudei** [comment]
Fixed with #343. Need review. Thanks
