### ISSUE TITLE
Instagram icon update

### ISSUE THREAD

**Issue by guillaumeberry** [antistatique/antistatique.net#326]
We need to update this tiny little icon for our Instagram account and in profile links.
It's probably just a Fontawesome or a Glyphicons update…

![update](https://cloud.githubusercontent.com/assets/1800253/15958351/5b7e99b2-2ef5-11e6-9136-670d2452cbd4.png)

Official source for Instagram brand: https://www.instagram-brand.com/

Ping me if you need help 😉

**Comment by tonifisler** [comment]
👍  an update to the `bower.json` and it's done. We should refactor the styleguide...
