### ISSUE TITLE
configure and run cron 😱

### ISSUE THREAD

**Issue by zufrieden** [antistatique/antistatique.net#329]
https://antistatique.net/fr/admin/reports/status

![screenshot 2016-07-26 08 04 46](https://cloud.githubusercontent.com/assets/451236/17127674/b4eb6e90-5307-11e6-81e7-c847ceeca501.png)

**Comment by Sudei** [comment]
For now, the crontab used the url to run cron.
```
* */2 * * * wget -O - -q -t 1 http://antistatique.net/cron.php?cron_key=HHRHO-dab5vCb6enY7ainSGT5cGjsY6i7wO36eXU6Kc
```

But the cron_key might change and it don't run anymore.

I use drush to run cron with
```
* */2 * * * /home/antistatique/www/antistatique.net/shared/drush/drush -r /home/antistatique/www/antistatique.net/current/drupal cron
```
