### ISSUE TITLE
Title overlapping all header on mobile when too long

### ISSUE THREAD

**Issue by ArnaudMathier** [antistatique/antistatique.net#337]
Bonjour, 
En voulant ouvrir un article depuis mon Android avec Chrome je suis tombé sur un petit bug d'affichage. 
Voilà...
Salut.
![screenshot_2016-08-04-06-47-00](https://cloud.githubusercontent.com/assets/19795690/17391589/93be9622-5a17-11e6-9514-f5a2fc744b0f.png)

**Comment by Sudei** [comment]
First fix with #338. Some review ? @Yago & @tonifisler
