### ISSUE TITLE
Create Highrise deal in the Trello Board "AS Mandats"

### ISSUE THREAD

**Issue by Saniha** [antistatique/antistatique.net#346]
The deals are actually created in this board, but only once "won". 
We want to have them created in Trello, once Created in Highrise. Thanks!

@gido 
cc @nsz @zufrieden @KidValdez @guillaumeberry @ArnaudMathier @julienbalsiger @Yago 

https://trello.com/b/Njpw2HWN/as-mandats

**Comment by zufrieden** [comment]
not the right repostory please look here https://github.com/antistatique/37sync/commits/feature/create-trello-card-when-deal-is-created

**Comment by Saniha** [comment]
Ooops thank you!
