### ISSUE TITLE
Strange / ugly client logos render on Chrome 54.0.2840.98

### ISSUE THREAD

**Issue by guillaumeberry** [antistatique/antistatique.net#350]
Strang rendering of client logos:
- Example page: https://antistatique.net/fr/nous/faisons/de-la-strategie-digitale
- Capture attached

🙉  💋 
![ouch](https://cloud.githubusercontent.com/assets/1800253/20431908/f1918f38-ad9c-11e6-9671-eca5eeab0b1f.png)

**Comment by jminguely** [comment]
It's even worst right now. No client at all:

<img width="1219" alt="capture d ecran 2017-04-03 a 10 23 30" src="https://cloud.githubusercontent.com/assets/2260030/24601042/b1575170-1857-11e7-9aa7-6d18d77fd3ff.png">

Solution.
Edit this content
http://antistatique.net/fr/admin/structure/block/manage/block/12/configure
With that
https://github.com/antistatique/antistatique.net/blob/0d5c9c245f2def7c3856f63ab723f6d15215cecf/drupal/sites/all/themes/antistatique/assets/components/molecules/list-clients.html.swig

**Comment by tonifisler** [comment]
I'll fix this today. Weird, I thought this had been done. 🤔

**Comment by tonifisler** [comment]
I knew it!

![screen shot 2017-04-03 at 10 41 36](https://cloud.githubusercontent.com/assets/1708450/24601684/2d040140-185a-11e7-9934-a7b8d996d855.png)

**Comment by tonifisler** [comment]
Done! Thanks @jminguely <3
