### ISSUE TITLE
A11y ☝️😎👍

### ISSUE THREAD

**Issue by jminguely** [antistatique/antistatique.net#351]
- [x] Add access key to main element in every page
- [x] Generate a complete menu (don't have to contain all the items, more a exemple purpose) with only `<nav role="navigation"><ul><li><a>` hidden for the rest of us but ARIA visible.
- [x] Every section (search, navigation, content, related-content, side-navigation, footer) should have a `h2.sr-only` with the correct name.
- [x] Every button must have a `aria-label=""`

**Comment by tonifisler** [comment]
@jminguely check issue #249 too, we need `alt` attributes on all images.
