### ISSUE TITLE
Job offer on the page "avec vous"

### ISSUE THREAD

**Issue by emusio** [antistatique/antistatique.net#372]
Mettre un lien sur la page "you" dans la page "avec vous" : plus logique pour qqn qui visite le site et qui se considère comme "vous" et pas "nous" :)

**Comment by gido** [comment]
Easy fix:

<img width="801" alt="screen shot 2018-07-03 at 18 29 15" src="https://user-images.githubusercontent.com/101859/42232544-0427106c-7eef-11e8-95a2-3c65beeae36e.png">
