### ISSUE TITLE
Phone number not appearing in English

### ISSUE THREAD

**Issue by guillaumeberry** [antistatique/antistatique.net#374]
Phones are displayed in the French version, not in the English one… 🤔

![fr](https://cloud.githubusercontent.com/assets/1800253/26630554/8056ab1a-4607-11e7-8865-18f1750dc89b.png)
![en](https://cloud.githubusercontent.com/assets/1800253/26630555/80721468-4607-11e7-8158-0cb5f2ec5220.png)

**Comment by gido** [comment]
Thanks @guillaumeberry for the report.

Fixed !
