### ISSUE TITLE
On skill page related-user listing need a clearfix in the grid

### ISSUE THREAD

**Issue by zufrieden** [antistatique/antistatique.net#378]
Image worth a thousand words ...

<img width="1525" alt="screenshot 2017-10-18 12 30 39" src="https://user-images.githubusercontent.com/451236/31713986-6c2e61e8-b400-11e7-96a2-45a41fb943b0.png">

Alexis is too big ? Or is he ?

**Comment by guillaumeberry** [comment]
@zufrieden Moi je vois surtout qu'on va devoir harmoniser les Job titles ;)
