### ISSUE TITLE
Define image formats

### ISSUE THREAD

**Issue by zufrieden** [antistatique/antistatique.net#49]

**Comment by guillaumeberry** [comment]
Hero:
[ ] Mobile 10:9
[ ] Tablet 16:10
[ ] Desktop 16:9

Paragraph:
[ ] Width: column width
[ ] Height: no limit
[ ] Maybe think of an height crop thingy for very long image (like it overpasses 4:1) like in Pinterest grid

Does it help @zufrieden ?

**Comment by mariontame** [comment]
2600 px Large

**Comment by guillaumeberry** [comment]
**2600 px** ? Wow, that's huge!

**Comment by guillaumeberry** [comment]
— Photos › **JPG**
— Graphique / dataviz / motifs › **PNG 8 / 24** ou **GIF**
— Animations › **GIF** powa !

**Comment by guillaumeberry** [comment]
- [ ] on gère les **vidéos** d'arrière plan ? (si oui @sepmil défini le format / résolution / encodage)
Poke @zufrieden @tonifisler

**Comment by tonifisler** [comment]
Like. Ce pourrait être cool.

**Comment by tonifisler** [comment]
**2600px** -> more future-proof!

**Comment by guillaumeberry** [comment]
**2600 x 1463 px** it is! :ok_hand:

**Comment by mariontame** [comment]
Desktop pictures are done ! I need to know the width size for mobile and tablet  ! :)

**Comment by guillaumeberry** [comment]
Currently we are not making mobile & tablet images:
we need to discuss if the CMS is generating lower resolution images.

Right @gido / @zufrieden / @tonifisler ?

**Comment by tonifisler** [comment]
@guillaumeberry @mariontame We're going to try to use the [picture](https://www.drupal.org/project/picture) module. It's based on Bootstrap breakpoints (or the ones we want) to change the images it's loading.

**Comment by guillaumeberry** [comment]
That's my man @tonifisler ! :+1:

**Comment by tonifisler** [comment]
Je comprends pas ton commit @zufrieden. On a défini des images à **2600 x 1463 px**, mais tu as mis **1600 x 900 px**. Voulu?

**Comment by gido** [comment]
Au risque de me répéter: N'hésitez pas à faire des PR et faire des reviews.
Meme rapide.



*--Antistatique*
Gilles Doge
+41 21 623 63 03
+41 78 810 67 66
www.antistatique.net

**Comment by zufrieden** [comment]
@tonifisler same ratio. 1600 x 900 Is more realist and OK as a minimum... WDYT ?

**Comment by tonifisler** [comment]
Yes we ask a minimum of **1600x900** :+1:
