### ISSUE TITLE
Project

### ISSUE THREAD

**Issue by tonifisler** [antistatique/antistatique.net#5]
https://projects.invisionapp.com/d/main#/console/1442313/54654756/preview

### Fields

| Field | Type | Full | Teaser | Testimonial | Required | Comment |
|-------|------|:----:|:------:|:-------:|:--------:|:---------------|
| title | text | ✔︎ | ✔︎ | | Yes | max 128 caractères |
| hero-image | image | ✔︎ | ✔︎ | | Yes | paysage - min 1500 px de large - random pattern si pas d'upload ou HEX |
| client | ~~Entity Reference, see #10~~ text | ✔︎ | ✔︎ | | Yes | ~~See comment **1**~~ |
| company name | text | ✔︎ | ✔︎ | | Yes | |
| company logo | image | ✔︎ | ✔︎ | | Yes | Carré - min 256 px - upload SVG et PNG |
| skills | Term Reference | ✔︎ | | | Yes | basé sur les services level 1 (stratégie, design, tech, etc.) |
| URL | Link (multiple) | ✔︎ | | | Yes | URL site ou Store d'app — plusieurs URL possibles|
| year | date | ✔︎ | ✔︎ | | Yes | |
| body | body + excerpt | ✔︎ | | | Yes |
| images | image (multiple) | ✔︎ | | | | —> Images to insert in body |
| testimonial name | text | ✔︎ | | ✔︎ | | Nom du contact chez le client |
| testimonial position | text | ✔︎ | | ✔︎ | | Nom du poste du contact |
| testimonial quote | text | ✔︎ | | ✔︎ | | Citation entre “ ” |
| testimonial avatar | image | ✔︎ | | ✔︎ | | Carré - min 256 px|
| Credits | Long Text | ✔︎ | | | | Photos, ressources, aides, etc |
| promoted to front page | default option | | | | Yes | |
| Stick to the top | default option | | | | | Sera en haut de liste page projet |

### Questions

- ~~**1** – What about the client? Does he have a page? Otherwise, just a Link field or Text field would be~~
- ~~**2** – Service content type? Basic Page?~~

### To also be displayed

| Thing | Full | Teaser | Comment |
|-------|:----:|:------:|---------|
| More projects | ✔︎ | | views based on skills / services ? |

**Comment by tonifisler** [comment]
@gido @zufrieden @guillaumeberry So we decided to remove the **Client** entity. So I replace it by a text field or just remove it plain and simple because we will tell the client name in the **Title** field?

=> Title field = **`Client Name > Project Name`** ?

**Comment by zufrieden** [comment]
@tonifisler add a client field (text)

**Comment by tonifisler** [comment]
@zufrieden Ok so using the **company name** field for that.

**Comment by tonifisler** [comment]
Or not. Company could be different than client. @zufrieden Correct?

**Comment by gido** [comment]
@tonifisler my review:

 - [ ] Remove `Company Name` field
 - [ ] Remove `Company Logo` field
 - [ ] Rename `Testimonial Name` into `Testimonial Author` ?
 - [ ] Missing `testimonial position`.
 - [ ] Missing `services`. Do you want to create a new ticket for this ?

**Comment by zufrieden** [comment]
Services are skills first level .. kind of
