### ISSUE TITLE
Portfolio Cardis Immobilier

### ISSUE THREAD

**Issue by KidValdez** [antistatique/antistatique.net#68]
http://antistatique.net/fr/portfolio/cardis

**Comment by sepmil** [comment]
L'image avec le bateau ecris dessus cardis n'est pas du tout au bon ratio et dimensions (bien qu'elle soit grande...) du coup ne correspond pas du tout aux dimensions qu'on aimerait mettre actuellement.  dure de trouver une image de bateau avec ecris dessus Cardis.. :-/ solution ?

**Comment by tonifisler** [comment]
Will be done in #184.
