### ISSUE TITLE
List of skills

### ISSUE THREAD

**Issue by gido** [antistatique/antistatique.net#9]
* Branding
 * Social media
 * Design
 * User Experience
 * Responsive
 * Development ?
 * Symfony
 * Magento
 * PHP
 * Wordpress
 * Event
 * E-commerce
 * Charity
 * **Add Your Own**

Keep in mind that we can't choose more than 3 skills per project (design and UX limitation).

**Comment by tonifisler** [comment]
Make those skills translatable!
